spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springTest
    password: 1111

  jpa:
    database: mysql
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
